import { useEffect, useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ArcaneBackground } from '@/components/arcane/ArcaneBackground';
import { ArcaneSeal } from '@/components/arcane/ArcaneSeal';
import { RuneCircle } from '@/components/arcane/RuneCircle';
import { FileDown, Scroll, Database, BookOpen } from 'lucide-react';

interface SessionData {
  projectConfig: {
    name: string;
    instructions: string;
  };
  visitedPages: string[];
  pageCache: Map<string, string>;
  generationPrompts: string[];
  sessionStartTime: Date;
}

// Animated counter hook
function useCountUp(target: number, duration: number = 1500) {
  const [value, setValue] = useState(0);
  const startedRef = useRef(false);

  useEffect(() => {
    if (startedRef.current || target === 0) return;
    startedRef.current = true;

    const startTime = performance.now();
    const step = (currentTime: number) => {
      const elapsed = currentTime - startTime;
      const progress = Math.min(elapsed / duration, 1);
      // Ease-out cubic
      const eased = 1 - Math.pow(1 - progress, 3);
      setValue(Math.round(eased * target));
      if (progress < 1) {
        requestAnimationFrame(step);
      }
    };
    requestAnimationFrame(step);
  }, [target, duration]);

  return value;
}

export default function ExportPage() {
  const navigate = useNavigate();
  const [sessionData, setSessionData] = useState<SessionData | null>(null);
  const [sessionDuration, setSessionDuration] = useState<number>(0);

  useEffect(() => {
    const storedData = localStorage.getItem('exportSessionData');
    if (storedData) {
      const parsed = JSON.parse(storedData);
      const pageCache = new Map(Object.entries(parsed.pageCache || {}));
      const sessionStartTime = new Date(parsed.sessionStartTime);

      const fullSessionData = {
        ...parsed,
        pageCache,
        sessionStartTime
      };

      setSessionData(fullSessionData);
      setSessionDuration(Math.round((new Date().getTime() - sessionStartTime.getTime()) / 1000 / 60));
    } else {
      navigate('/');
    }
  }, [navigate]);

  const handleDownload = (downloadType: string) => {
    if (!sessionData) return;

    switch (downloadType) {
      case 'projectFiles': {
        const files = Array.from(sessionData.pageCache.entries()).map(([path, content]) => {
          const filename = path === '/' ? 'index.html' : path.replace('/', '') + '.html';
          return { filename, content };
        });
        files.forEach(file => {
          const blob = new Blob([file.content], { type: 'text/html' });
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = file.filename;
          a.click();
          URL.revokeObjectURL(url);
        });
        break;
      }
      case 'promptLog': {
        const logContent = [
          "ThisProjectDoesNotExist - AI Generation Log",
          "=".repeat(50),
          "Project: " + sessionData.projectConfig.name,
          "Instructions: " + (sessionData.projectConfig.instructions || "None provided"),
          "Session Start: " + sessionData.sessionStartTime,
          "Total Pages: " + sessionData.visitedPages.length,
          "",
          "Generation Prompts:",
          "=".repeat(20),
          ...sessionData.generationPrompts,
          "",
          "Visited Pages:",
          "=".repeat(15),
          ...sessionData.visitedPages.map((page: string) => "- " + page),
          "",
          "Generated by ThisProjectDoesNotExist"
        ].join("\n");
        const logBlob = new Blob([logContent], { type: 'text/plain' });
        const logUrl = URL.createObjectURL(logBlob);
        const logA = document.createElement('a');
        logA.href = logUrl;
        logA.download = sessionData.projectConfig.name.replace(/\s+/g, '_') + '_generation_log.txt';
        logA.click();
        URL.revokeObjectURL(logUrl);
        break;
      }
      case 'fullSession': {
        const exportData = {
          ...sessionData,
          pageCache: Object.fromEntries(sessionData.pageCache)
        };
        const sessionBlob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
        const sessionUrl = URL.createObjectURL(sessionBlob);
        const sessionA = document.createElement('a');
        sessionA.href = sessionUrl;
        sessionA.download = sessionData.projectConfig.name.replace(/\s+/g, '_') + '_session.json';
        sessionA.click();
        URL.revokeObjectURL(sessionUrl);
        break;
      }
    }
  };

  const handleStartNewSession = () => {
    localStorage.removeItem('exportSessionData');
    localStorage.removeItem('projectConfig');
    navigate('/');
  };

  // Count-up values
  const pagesCount = useCountUp(sessionData?.visitedPages.length ?? 0);
  const minutesCount = useCountUp(sessionDuration);
  const spellsCount = useCountUp(sessionData?.generationPrompts.length ?? 0);

  if (!sessionData) {
    return (
      <ArcaneBackground>
        <div className="min-h-screen flex items-center justify-center">
          <div className="text-center">
            <RuneCircle size={60} className="mx-auto mb-6" />
            <h1 className="font-cinzel text-lg text-[#e8dcc8] mb-2">Preparing the Seal...</h1>
            <p className="text-[#9a8c7a] text-sm italic">Loading your grimoire data</p>
          </div>
        </div>
      </ArcaneBackground>
    );
  }

  return (
    <ArcaneBackground>
      <div className="min-h-screen p-6">
        <div className="max-w-4xl mx-auto animate-[fade-in_0.6s_ease-out]">

          {/* Header with Seal */}
          <div className="text-center mb-10">
            <ArcaneSeal size={100} className="mx-auto mb-6" />
            <h1 className="font-cinzel text-3xl sm:text-4xl font-bold text-[#f0c75e] text-gold-shimmer mb-3">
              Your Grimoire is Complete
            </h1>
            <p className="text-[#9a8c7a] text-lg italic max-w-2xl mx-auto">
              The pages you've conjured are ready to enter the mortal realm
            </p>
            <p className="text-[#d4a843] font-cinzel mt-2">
              {sessionData.projectConfig.name}
            </p>
          </div>

          {/* Stats as Enchanted Gems */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
            {[
              { value: pagesCount, label: "Pages Conjured", delay: "0s" },
              { value: minutesCount, label: "Minutes of Sorcery", delay: "0.15s" },
              { value: spellsCount, label: "Spells Cast", delay: "0.3s" },
            ].map(({ value, label, delay }) => (
              <Card
                key={label}
                className="bg-[#1e1233]/80 border-[rgba(212,168,67,0.15)] shadow-[inset_0_0_20px_rgba(212,168,67,0.05)]"
                style={{ animation: `bob 3s ${delay} ease-in-out infinite` }}
              >
                <CardContent className="p-6 text-center">
                  <div className="font-cinzel text-4xl font-bold text-[#f0c75e] mb-2">{value}</div>
                  <div className="text-[#9a8c7a] text-sm rune-label">{label}</div>
                </CardContent>
              </Card>
            ))}
          </div>

          {/* Download Section */}
          <Card className="bg-[#1e1233]/60 border-[rgba(139,92,246,0.15)] mb-8">
            <CardHeader>
              <CardTitle className="font-cinzel text-xl text-[#f0c75e]">Extract Your Creations</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {[
                  { icon: FileDown, label: "HTML Scrolls", sub: "(.html files)", action: 'projectFiles' },
                  { icon: Scroll, label: "Incantation Log", sub: "(.txt file)", action: 'promptLog' },
                  { icon: Database, label: "Session Tome", sub: "(.json file)", action: 'fullSession' },
                ].map(({ icon: Icon, label, sub, action }) => (
                  <Button
                    key={action}
                    onClick={() => handleDownload(action)}
                    className="h-auto p-5 flex flex-col items-center gap-3 bg-[#2a1845]/60 border border-[rgba(212,168,67,0.15)] text-[#e8dcc8] hover:border-[#d4a843]/40 hover:shadow-[0_0_15px_rgba(212,168,67,0.15)] hover:-translate-y-0.5 transition-all duration-500"
                  >
                    <Icon className="w-6 h-6 text-[#d4a843]" />
                    <div className="text-center">
                      <div className="font-semibold text-sm">{label}</div>
                      <div className="text-xs text-[#9a8c7a]">{sub}</div>
                    </div>
                  </Button>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Pages Generated */}
          <Card className="bg-[#1e1233]/60 border-[rgba(139,92,246,0.15)] mb-8">
            <CardHeader>
              <CardTitle className="font-cinzel text-lg text-[#e8dcc8]">Pages Conjured</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {sessionData.visitedPages.map((page, index) => (
                  <div key={index} className="bg-[#2a1845]/40 rounded-lg p-3 text-center border border-[rgba(139,92,246,0.1)]">
                    <div className="flex items-center justify-center gap-2">
                      <span className="text-[#d4a843] text-[8px]">◆</span>
                      <span className="text-[#e8dcc8] font-mono text-sm">
                        {page === '/' ? 'index.html' : page.replace('/', '') + '.html'}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* New Session */}
          <div className="text-center">
            <Button
              onClick={handleStartNewSession}
              variant="outline"
              className="font-cinzel border-[#d4a843]/40 text-[#d4a843] hover:bg-[#d4a843]/10 hover:border-[#d4a843]/60 transition-all duration-300 px-8"
            >
              <BookOpen className="w-4 h-4 mr-2" />
              Open a New Grimoire
            </Button>
          </div>
        </div>
      </div>
    </ArcaneBackground>
  );
}
