const examples = [
  "Lunar Café",
  "Velocity Labs",
  "The Midnight Bakery",
  "Neon Drift Racing",
  "Pocket Galaxy",
  "Wanderlust Travel Co.",
  "Iron & Oak Furniture",
  "Synthwave Radio",
  "Cloud Nine Yoga",
  "Pixel Forge Studios",
  "The Hungry Algorithm",
  "Aurora Skincare",
  "Basement Records",
  "Terraform Landscaping",
  "Cipher Security",
  "Nomad Coffee Roasters",
  "Prism Architecture",
  "Deep Blue Diving",
  "The Reading Room",
  "Bolt Delivery",
  "Evergreen Botanics",
  "Signal Magazine",
  "Zenith Fitness",
  "Folklore Brewing Co.",
  "Starline Cinema",
  "Mosaic Learning",
  "Ridgeline Outdoors",
  "Ember & Stone Pizza",
  "Parallel Finance",
  "Dawnlight Photography",
];

export function generateRandomName(): string {
  return examples[Math.floor(Math.random() * examples.length)];
}
