const projectTypes = [
  "Todo List",
  "Weather App",
  "Notes App",
  "Calculator",
  "Calendar App",
  "Recipe Manager",
  "Expense Tracker",
  "Password Manager",
  "Contact Manager",
  "Chat Application",
  "Blog Platform",
  "E-commerce Store",
  "Social Media App",
  "Music Player",
  "Photo Gallery",
  "File Manager",
  "Text Editor",
  "Code Editor",
  "Project Manager",
  "Time Tracker",
  "Habit Tracker",
  "Fitness Tracker",
  "Learning Platform",
  "Quiz App",
  "Survey Tool",
  "Invoice Generator",
  "Resume Builder",
  "Portfolio Website",
  "News Reader",
  "Bookmark Manager",
  "URL Shortener",
  "QR Code Generator",
  "Color Palette Tool",
  "Image Editor",
  "Video Player",
  "Podcast Player",
  "Meditation App",
  "Travel Planner",
  "Event Manager",
  "Restaurant Finder",
  "Real Estate App",
  "Job Board",
  "Dating App",
  "Gaming Platform",
  "Streaming Service"
];

export function generateRandomName(): string {
  const randomProject = projectTypes[Math.floor(Math.random() * projectTypes.length)];
  return randomProject;
}
